--Scenario 1: Adding two columns to the DimCourse Table with Rand and Randbetween functions

EVALUATE
(

ADDCOLUMNS(

DimCourse,

"Random value", rand(),--Between 0 and 1 any value

"Random between", RANDBETWEEN(200,300) --between 200 and 300 any value

)
)
--Scenario 2 : Multiplying all values of EHIKE using Product function

EVALUATE
(

row(
"Product of duration", product(TEST[EHIKE])
)
)

--
EVALUATE
(
Row
(
"Least common multiple", LCM(2,4),
"Greatest Common Divisor", GCD(2,4),
"EVen", even(3),
"Odd",Odd(2),
"Sum of DF", Sum(FactPayments[Discount_Fee]),
"Division", Divide(25,5),
"Division 1", IFERROR(Divide(25,0),99)
)
)











